### PR TITLE
Include third-party libraries in the repository as submodules.

### PR DESCRIPTION
**Pull request by CrossVR**
This makes things easier to compile and removes the need for an environment variable.

I also included the DX8 GUID static library so you don't have to overwrite system libraries.

### CODE REVIEW

**Comment by nitrocaster** [comment]
Thanks for your contribution, I'll check it soon.

**Comment by CrossVR** [comment]
Ideally other libraries like libjpeg should also be included in the solution and compiled from source like I did with zlib here, but that's for another PR.

@nitrocaster I've seen the version plan, but what exactly are the goals for the project? The way I see it is to provide support for this great game now that the developers are gone and attempt to port it to different platforms.

And ofcourse to be a good base for people to mod the game, though I think mods should be restricted to forks so that this project stays true to the original.

**Comment by CrossVR** [comment]
libjpeg was causing problems in the Release configuration, so I also put that in a submodule now. Just BugTrap and OpenAutomate left now.

**Comment by nitrocaster** [comment]
First of all, the main goal is to fix bugs.
I'm not sure if I would maintain XRay 1.5, because there's XRay 1.6. So, if we discuss any plans, I consider that to refer to XRay 1.6.

**Comment by CrossVR** [comment]
I'm mostly interested in version 1.5 though, as Clear Sky was my personal
favourite. Though now that we have the source code, would it be possible to
thoroughly upgrade the Clear Sky engine to 1.6?

**Comment by CrossVR** [comment]
And that's the final one, all dependencies are included as a submodule now and compiled to the libraries/binaries folder.

**Comment by CrossVR** [comment]
Okay, the solution builds correctly now. I'm done making my changes for this PR, you can review it.

**Pull request merged**
